<br>
<br>

# `# Text Vectorization:`

- 01: OHE
- 02: BoW
- 03: Bag of N-gram
- 04: Tf-Idf

<br>
<br>



<br>

# `01 OHE:`

<br>

<br>

# `02 BAG OF Words:`

<br>

In [2]:

import numpy as np 
import pandas as pd 

In [3]:

df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:


from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [5]:

# vocubabulary:
cv.vocabulary_ # 0,1,2,3,4 is the ordering


{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [6]:

# vector of 0th index in df (people watch campusx): 
# from vocab, if we have, people and it's index 2 that means in array 
# {0,1,2,3,4}
# {0 0 1 0 0 }


# so,  (people watch campusx)
# {'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}
# from vocab: 0-> campusx have in our sentence 0th index: 1
# from vocab: 1-> commnet haven't in our sentence 1st index: 0
# from vocab: 2-> people, have in our sentence 2nd index: 1
# from vocab: 3-> watch, have in our sentence 3nd index: 1
# from vocab: 4-> write, haven't in our sentence 2nd index: 0

bow[0].toarray()


array([[1, 0, 1, 1, 0]])

In [7]:

print(bow[2])
print()

# why toarray() bacuse, sklearn give us sparse matrix we need to convert it to array.
print(cv.vocabulary_)
bow[1].toarray()
# campusx watch campusx


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 5)>
  Coords	Values
  (0, 2)	1
  (0, 4)	1
  (0, 1)	1

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


array([[2, 0, 0, 1, 0]])

In [8]:

# bag of words can control OOV:
cv.transform(["campusx watch campusx and  yasin arafat write comment of campusx"]).toarray()
# here, we have "yasin,arafat and, of", but don't get `**Out Of Vocavulary Error**`



array([[3, 1, 0, 1, 1]])

<br>

## #parameter of countvectorizer()

<br>


`1st go to the documentation:`

lowercase=True,  
preprocessor=None, <br>
tokenizer=None, <br>
stop_words=None: 
<br>

**We can define our own lowercase,preprocssor,tokenizer and stop_words যেইটা আমরা text preprocessing এ করে থাকি  ।** 
<br>

ngram_range=(1, 1): **We will see this later** <br>
binary: true, default: false:  **Used in sentiment analysis:** <br>
max_feture: 1,2,3,4: **see note**

In [9]:

# example of binary: true

# if we set binary=ture then if (frequency>1) then value=1:
# 1 means words exist 
# 0 means words is not exist, if binary=True
# while doing sentiment analysis it's good

cv1 = CountVectorizer(binary=True)
cv1.fit_transform(df['text'])
print(cv1.vocabulary_)
cv1.transform(["campusx watch campusx and  yasin arafat write comment of campusx"]).toarray()



{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


array([[1, 1, 0, 1, 1]])

In [10]:

# max feature: it takes only the campusx:
# by using this we can ignore reare words when we will work on a big dataset

cv1 = CountVectorizer(binary=True,max_features=1)
cv1.fit_transform(df['text'])
print(cv1.vocabulary_)
cv1.transform(["campusx watch campusx and  yasin arafat write comment of campusx"]).toarray()


{'campusx': np.int64(0)}


array([[1]])

<br>

# `03 BAG OF N-Gram:`

<br>

In [ ]:

# bigram:
cv3 = CountVectorizer(ngram_range=(2,2)) 
bow = cv3.fit_transform(df['text'])
print(df['text'][0])
print(cv3.vocabulary_)
bow[0].toarray()


people watch campusx
{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


array([[0, 0, 1, 0, 1, 0]])

In [ ]:

# unigram+bigram
cv3 = CountVectorizer(ngram_range=(1,2))
bow = cv3.fit_transform(df['text'])
print(df['text'][0])
print(cv3.vocabulary_)
bow[0].toarray()


people watch campusx
{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


array([[1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0]])

In [13]:

len(cv3.vocabulary_)


11

<br>
<br>

# `#04 Tf-Idf:`

<br>

**See the documentation.**

<br>

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

# tf-idf value for the documents:
tfidf.fit_transform(raw_documents=df['text']).toarray()


array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [19]:

# Calcuation of idf: in sklearn they add+1: 
print(tfidf.get_feature_names_out())
tfidf.idf_


['campusx' 'comment' 'people' 'watch' 'write']


array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])